### ISSUE TITLE
Api to get particular crash session

### ISSUE THREAD

**Issue by nesterov-n** [strongself/fabricio#26]
Hello.

First of all, thanks for this brilliant tool!
It's so convenient and useful!

It would be great if you add ability to download list of particular crash sessions from fabric.

Sorry, I don;'t understand Ruby language at all. Therefore I can't prepare PR by myself.

**Comment by etolstoy** [comment]
Well, there is a problem. The detail issue request doesn't show all incidents ids, only the latest one:

```
        "_issue48yZVW": {
          "externalId": "58d33b170aeb16625bba3eae",
          "createdAt": 1490238231,
          "type": "crash",
          "state": "open",
          "latestSessionId": "9d04a49702dc4527a20c0c9e9b5f7cf3_393628d8472742a6af9e4529cbc17858_0_v1",
          ...
```

Unfortunately, don't see any way to download all incidents at the moment.

**Comment by CognitiveDisson** [comment]
#27
