### ISSUE TITLE
 client.app.single_issue not working

### ISSUE THREAD

**Issue by mmoser18** [strongself/fabricio#28]
Hi - I am trying to write me a utility that automatically downloads the logfile of a selected issue but I am having trouble with the "single_issue" method. It always only yields me e.g.:

> single_issue for app 53f20a3d44e4b41b7b000020 and externalId 582cd8600aeb16625beff9f5:
> C:/Users/mmo/test/CrashlyticsLogCollector/fabricio/services/app_service.rb:152:in `single_issue': undefined method `[]' for nil:NilClass (NoMethodError)
>         from CrashlyticsLogCollector.rb:39:in `&lt;main&gt;'

I interpret this such, that fabricio can't find the issue (hence the nil) and that the "undefined '[]'" on that object is then just a consequence of that.

To test I am first fetching the top issue using "top_issues" (which works and returns an issue - so that issue definitely exists!) and then I am using the "externalId" value of that issue to call the "client.app.single_issue('app_id', 'issue_external_id', start_timestamp, end_timestamp)" method, which then yields me the above error.

I append my code snippet below (it's purposely a bit longish and verbose...)

Any idea what I am missing? Am I using the wrong id (I also tried the other ids available in the issue object ("id", "displayId") but that didn't work, either)? Or is this method broken?

Regards,
Michael

```
...
end_timestamp = Date.today
start_timestamp = (end_timestamp - 90)

puts "top-issue last 90 days:\n"
top_issues = client.app.top_issues(app_id, start_timestamp.to_time.to_i, end_timestamp.to_time.to_i, ['all'], 1)
top_issue = top_issues[0]
puts top_issue.to_yaml

externalId = top_issue.externalId
puts "single_issue for app " + app_id + " and externalId " + externalId + ":\n"
single_issue = client.app.single_issue(app_id, externalId, start_timestamp, end_timestamp) 
puts single_issue.to_yaml
```

**Comment by etolstoy** [comment]
Hi @mmoser18. That's really strange – the `single_issue` works perfectly for me. Do you experience this issue with all crashes?

**Comment by etolstoy** [comment]
Closing because of insufficient data.
