### ISSUE TITLE
Monthly Active Users

### ISSUE THREAD

**Issue by Fr4ncis** [strongself/fabricio#30]
Hi, 
First of all thank you, the gem works great!
It seems like there is no API call for MAUs, that is odd. I just tried to modify the gem to call the API with monthly_active instead of daily_active but that does not seem to work (API returns 504 Gateway Timeout).
Next, I am trying to see if I can intercept the call from my phone with Charles.
How did you scrape the API, any insights or ideas on how to find the MAU call?

**Comment by Fr4ncis** [comment]
Long story short, the app uses another API (and it seems to use certificate pinning so I reconsidered my options). Looking more carefully at the webpage, I can see it makes requests among which `https://www.fabric.io/api/v2/organizations/{{organisationID}}/apps/{{appID}}/growth_analytics/monthly_active.json?start=1497139200&end=1499731200&build=all` which tells me the problem with monthly_active.json is merely the time span being too big for the request causing the Gateway Timeout.

**Comment by Fr4ncis** [comment]
Tested and made a PR. 😁

**Comment by etolstoy** [comment]
Thanks for your PR. I've just released a new version.
