### ISSUE TITLE
Api with curl command is throwing below error to get the access token

### ISSUE THREAD

**Issue by chiranjeevi** [strongself/fabricio#32]
Here is the curl command 
body='{ "type": "string",  "default": "{\"grant_type\":\"password\",\"scope\":\"organizations apps issues features account twitter_client_apps beta software answers\",\"username\":\"XXXX@XXXX.com\",\"password\":\"XXXX\",\"client_id\":\"client_id\",\"client_secret\":\"client_secret\"}"  }'

curl -X POST "https://fabric.io/oauth/token" -H "Content-Type: application/json" --data-raw "$body"

output: {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed.","status":"unauthorized"}

by the way I didn't understand, what needs to be feeded for client_id and client_secret properties in body
I really appreciate a faster reply

**Comment by CognitiveDisson** [comment]
Client_id and client_secret are the identifiers of your client. You can get it by sniffing requests from the site or from a mobile application. Since this is not a public API.  Or you can look it up [in the code](https://github.com/strongself/fabricio/blob/develop/lib/fabricio/client/client.rb) of this project.

**Comment by chiranjeevi** [comment]
I have tried with given client id and secret key, still I get the same error
body='{ "type": "string",  "default": "{\"grant_type\":\"password\",\"scope\":\"organizations apps issues features account twitter_client_apps beta software answers\",\"username\":\"XXXX@XXXX.com\",\"password\":\"XXXX\",\"client_id\":\"2c18f8a77609ee6bbac9e53f3768fedc45fb96be0dbcb41defa706dc57d9c931\",\"client_secret\":\"092ed1cdde336647b13d44178932cba10911577faf0eda894896188a7d900cc9\"}"  }'


![image](https://user-images.githubusercontent.com/1433660/28878809-4aa38a5c-7798-11e7-98d5-930560414334.png)

**Comment by CognitiveDisson** [comment]
`body='{"grant_type":"password","scope":"organizations apps issues features account twitter_client_apps beta software answers","username":"XXXX@XXXX.com","password":"XXXX","client_id":"2c18f8a77609ee6bbac9e53f3768fedc45fb96be0dbcb41defa706dc57d9c931","client_secret":"092ed1cdde336647b13d44178932cba10911577faf0eda894896188a7d900cc9"}'`

**Comment by chiranjeevi** [comment]
Thank you so much for correcting the body format. It responds with access token now.
Now I'm struck at fetching other api calls ( list of apps/organizations)
Correct me If I'm doing anything wrong

curl -X GET "https://fabric.io/api/v2/organizations" -H 'Authorization: Bearer {"XXXXXXXXXXXXXXX3b30fc63c7ce087b82480XXXX"}'

I get the output as 
{"message":"No account specified."}
not sure where exactly need to specify the account again in this curl command

**Comment by CognitiveDisson** [comment]
'Authorization' it is header field. In the header fields do not usually use json format.
Should be like this:
`curl -X GET "https://fabric.io/api/v2/organizations" -H 'Authorization: Bearer XXXXXXXXXXXXXXX3b30fc63c7ce087b82480XXXX'`

**Comment by chiranjeevi** [comment]
Awesome, Thanks so much all works fine now
Really appreciate prompt response.
