### ISSUE TITLE
client_id and client_secret

### ISSUE THREAD

**Issue by iuhh** [strongself/fabricio#42]
Very happy to find this package that allows easier access to fabric data.  Just wonder about the definition of those two parameters in client.rb, the comment says:
    # Default values for initialization parameters
    # clientId and clientSecret are taken from Android application.

Where can one find those value appropriate to their account?  I tried with our API Key as client_id and build secret as client_secret, and that didn't work.  Where in an Android app could I find that?

Many thanks.
H

**Comment by etolstoy** [comment]
Hi @iuhh ! These parameters are taken from the sources of Fabric iOS application. They are not unique for each account.

**Comment by mentapro** [comment]
@etolstoy Hi,
Could you please clarify, **client_id** and **client_secret** now have names "API Key" and "Build Secret" on "Organizations" page on fabric.io site? Or where can I find these values?
I have tried to inspect requests which my browser make to fabric.io but I didn't find any client_secret. There is only "API Key", "Organization ID", "Developer Token" and maybe some others.

I tried to make some request with "Api key" and "build secret" to 'https://fabric.io/oauth/token' but I have such response:
`{
    "error": "invalid_client",
    "error_description": "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.",
    "status": "unauthorized"
}`
