### ISSUE TITLE
undefined method `FileSessionStorage'

### ISSUE THREAD

**Issue by alex1x** [strongself/fabricio#54]
I have problems getting this to work. The most blocking one is this:

```
$ fabricio credential
Setup credential
We have to know you're email from fabric account
email:  a
Now we want your password. Do not be afraid, it is stored locally
password:  
/home/vagrant/.gem/ruby/gems/fabricio-1.3.0/lib/fabricio/cli/cli.rb:36:in `block in credential': undefined method `FileSessionStorage' for #<Fabricio::CLI:0x000000012efe18> (NoMethodError)
	from /home/vagrant/.gem/ruby/gems/fabricio-1.3.0/lib/fabricio/client/client.rb:61:in `initialize'
	from /home/vagrant/.gem/ruby/gems/fabricio-1.3.0/lib/fabricio/cli/cli.rb:33:in `new'
	from /home/vagrant/.gem/ruby/gems/fabricio-1.3.0/lib/fabricio/cli/cli.rb:33:in `credential'
	from /home/vagrant/.gem/ruby/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/vagrant/.gem/ruby/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/vagrant/.gem/ruby/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/vagrant/.gem/ruby/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/vagrant/.gem/ruby/gems/fabricio-1.3.0/bin/fabricio:4:in `<top (required)>'
	from /home/vagrant/bin/fabricio:23:in `load'
	from /home/vagrant/bin/fabricio:23:in `<main>'
```

I have tried this on Mac, Ubuntu, and Centos, on different versions of Ruby (2.3.0, 2.5.0, 2.0.0)... they all return this same error. 

I install by cloning your repo and running `make install`. I do this because no other way of installing works for me. I tried to create a Gemfile and put `gem 'fabricio'` and run `bundle`. This says that the installation of fabricio is successful but then the `fabricio` command is not available. If I do `gem which fabricio` and go to that dir, there is no `fabricio` executable. Same error occurs if I do `gem install fabricio`. This has been the same again on 3 OSes and Ruby versions. 

I don't know the first thing about Ruby so maybe I'm missing something very obvious... but I just want to programmatically get crash metrics.

I wasn't able to use your HTTP API either, as I cannot authenticate correctly: presumably it requires `client_id` and `client_secret` which I don't have. 

If you can help me either a) use the CLI / fix the `FileSessionStorage` error, or b) use the HTTP API that would be great.

Thanks.

**Comment by CognitiveDisson** [comment]
Hi.
In the development branch not a stable version. You can install the previous one - 1.3.0.
I will fix the problem in a few days.

**Comment by CognitiveDisson** [comment]
I fixed the problem. Try on the last commit

**Comment by alex1x** [comment]
Thank you, works much better now! I appreciate the quick reaction. Also I took client_id and client_secret from https://github.com/strongself/fabricio/blob/c9e645ab130b77c3f8d9e946d21c7751efbe993d/lib/fabricio/client/client.rb to work on API on my own. Let me know if there is better way.
