### ISSUE TITLE
getting undefined method `[]' for nil:NilClass when asking for crashes

### ISSUE THREAD

**Issue by RobsonKing** [strongself/fabricio#56]
been using the api for almost a year now, and this week starting getting an error fetching crashes.

```
  client = Fabricio::Client.new do |config|
      config.username = ENV['CRASHLYTICS_ACCOUNT']
      config.password = ENV['CRASHLYTICS_PASSWORD']
    end

app_id = 'blablabla'
start_date = Date.today -7.days
end_date = Date.today

 client.app.crashes(app_id, start_date , end_date, ['all'])

```
blows up with:

NoMethodError: undefined method `[]' for nil:NilClass
        from /Users/robson/.rvm/gems/ruby-2.3.3/gems/fabricio-1.3.0/lib/fabricio/services/app_service.rb:123:in `crashes'

Did the internal fabric api change?

**Comment by CognitiveDisson** [comment]
Try the latest version (last commit). It should work. Note that the syntax has changed.

Recently there have been changes in the API. The session update does not work now, but authorization and other requests should work. We are working on the correction of this problem. As soon as we fix this problem, we release a new version.

**Comment by CognitiveDisson** [comment]
@RobsonKing Check that you have confirmed the use of the GDPR.

**Comment by RobsonKing** [comment]
Good call!  That was exactly the problem.  Use a different account for running automation stuff and never acknowledged the GDPR.  Thanks!
