### ISSUE TITLE
When has coming a new release?

### ISSUE THREAD

**Issue by renatobenks-zz** [strongself/fabricio#61]
We were exploring the `fabricio` to take all events from our apps, however, in the current version, there are no resources available to do it. So, it's very important to know for us when will come to a new release with this resources to access events.

**Comment by etolstoy** [comment]
Hi, @renatobenks !
I'm not sure that it's a good idea to implement this functionality, because in the early 2019 it will entirely move to Firebase – https://get.fabric.io/roadmap. We're planning to investigate Firebase API shortly and to create our own roadmap of moving to it.

**Comment by etolstoy** [comment]
I've created a board with current status: https://github.com/strongself/fabricio/projects/1
